name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Build the Docker image
      run: make build
